# Generated by Django 3.1.4 on 2021-01-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownGapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=10)),
                ('market', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=100)),
                ('pm_volume', models.BigIntegerField()),
                ('pm_market_cap', models.BigIntegerField()),
                ('pm_shares_outstanding', models.BigIntegerField()),
                ('pm_float', models.BigIntegerField()),
                ('pm_held_insiders', models.FloatField()),
                ('pm_held_institutions', models.FloatField()),
                ('pm_short_float', models.FloatField(null=True)),
                ('pm_atr', models.FloatField()),
                ('pm_red_gaps', models.FloatField(null=True)),
                ('pm_observations', models.IntegerField()),
                ('pdah_volume', models.BigIntegerField()),
                ('pd_close', models.FloatField()),
                ('ac_market_cap', models.BigIntegerField()),
                ('volume', models.BigIntegerField()),
                ('gap_percentage', models.FloatField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('tr', models.FloatField()),
                ('move', models.FloatField()),
                ('ac_atr', models.FloatField()),
                ('prev_day_rvol', models.FloatField()),
                ('day_rvol', models.FloatField()),
                ('float_rotation', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UpGapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=10)),
                ('market', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=100)),
                ('pm_volume', models.BigIntegerField()),
                ('pm_market_cap', models.BigIntegerField()),
                ('pm_shares_outstanding', models.BigIntegerField()),
                ('pm_float', models.BigIntegerField()),
                ('pm_held_insiders', models.FloatField()),
                ('pm_held_institutions', models.FloatField()),
                ('pm_short_float', models.FloatField(null=True)),
                ('pm_atr', models.FloatField()),
                ('pm_red_gaps', models.FloatField(null=True)),
                ('pm_observations', models.IntegerField()),
                ('pdah_volume', models.BigIntegerField()),
                ('pd_close', models.FloatField()),
                ('ac_market_cap', models.BigIntegerField()),
                ('volume', models.BigIntegerField()),
                ('gap_percentage', models.FloatField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('tr', models.FloatField()),
                ('move', models.FloatField()),
                ('ac_atr', models.FloatField()),
                ('prev_day_rvol', models.FloatField()),
                ('day_rvol', models.FloatField()),
                ('float_rotation', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
