# Generated by Django 3.1.4 on 2021-03-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gappers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downgapper',
            name='last',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='upgapper',
            name='last',
            field=models.FloatField(null=True),
        ),
    ]
