# Generated by Django 3.2 on 2021-04-22 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gappers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downgapper',
            options={'ordering': ['date', '-gap_percentage']},
        ),
        migrations.AlterModelOptions(
            name='upgapper',
            options={'ordering': ['date', '-gap_percentage']},
        ),
        migrations.AlterUniqueTogether(
            name='downgapper',
            unique_together={('date', 'ticker')},
        ),
        migrations.AlterUniqueTogether(
            name='upgapper',
            unique_together={('date', 'ticker')},
        ),
    ]
