# Generated by Django 3.1.4 on 2021-03-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gappers', '0002_auto_20210320_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='downgapper',
            name='gap',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='upgapper',
            name='gap',
            field=models.FloatField(null=True),
        ),
    ]
