# Generated by Django 3.1.4 on 2021-04-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gappers', '0003_auto_20210320_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='downgapper',
            name='pm_s1_beta',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='upgapper',
            name='pm_s1_beta',
            field=models.FloatField(null=True),
        ),
    ]
