version: '3.8'
services:
    db:
        image: postgres:9.5
        container_name: db
        hostname: db
        env_file: ./devops/docker/db/.env
        volumes:
            - db_data:/var/lib/postgresql/
            - ./docker/backups/dumps/:/dumps/
        networks:
            - djangonetwork
    backend:
        build:
            context: ./backend/
            dockerfile: Dockerfile
        container_name: re_backend
        hostname: re_backend
        command: /usr/local/bin/gunicorn backend.wsgi:application -w 3 -b :8000 --reload --log-level debug --timeout 90
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/backend
        env_file: ./backend/.env
        depends_on:
            - db
        links:
            - db
            - redis
            - rabbit
        networks:
            - djangonetwork
    nginx:
        build: ./devops/docker/nginx/
        container_name: re_nginx
        hostname: re_nginx
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /www/static #static volume
            - ./devops/docker/nginx/sites/:/etc/nginx/conf.d
            - ./devops/docker/certbot/conf:/etc/letsencrypt/
            - ./devops/docker/certbot/www:/var/www/certbot
        volumes_from:
            - backend
        links:
            - backend:backend
        networks:
            - djangonetwork
    redis:
        restart: always
        image: redis:latest
        hostname: redis
        networks:
            - djangonetwork
    rabbit:
        image: rabbitmq:latest
        hostname: rabbit
        env_file: ./devops/docker/rabbit/.env
        ports:
          - "5672:5672"  # we forward this port because it's useful for debugging
          - "15672:15672"  # here, we can access rabbitmq management plugin
        networks:
            - djangonetwork
    certbot:
      image: certbot/certbot
      restart: unless-stopped
      container_name: re_certbot
      hostname: re_certbot
      volumes:
        - ./devops/docker/certbot/www:/var/www/certbot
        - ./devops/docker/certbot/conf:/etc/letsencrypt/
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    # Celery Worker
    worker:
        build:
            context: ./backend/
            dockerfile: Dockerfile
        command: ./wait-for-it.sh rabbit:5672 --timeout=30 -- celery -A backend worker -l info
        user: varveler
        container_name: re_worker
        hostname: re_worker
        volumes:
            - ./backend:/backend
        links:
            - db
            - rabbit
            - redis
        env_file: ./backend/.env
        environment:
          - LC_ALL=C.UTF-8
          - LANG=C.UTF-8
        depends_on:
            - rabbit
        networks:
            - djangonetwork

    # Celery beat
    beat:
        build:
            context: ./backend/
            dockerfile: Dockerfile
        command: ["./wait-for-it.sh", "db:5432", "--timeout=30", "--", "celery", "-A", "backend", "beat", "-l", "info", "-S", "django"]
        container_name: re_beat
        hostname: re_beat
        volumes:
            - ./backend:/backend
        links:
            - db
            - rabbit
            - redis
        env_file: ./backend/.env
        environment:
          - LC_ALL=C.UTF-8
          - LANG=C.UTF-8
        depends_on:
            - db
            - rabbit
        networks:
            - djangonetwork
volumes:
    db_data:
networks:
    djangonetwork:
        driver: bridge
