version: '3.8'
services:
    backend:
        environment:
            - DJANGO_SETTINGS_MODULE=backend.settings.production
    worker:
        environment:
            - DJANGO_SETTINGS_MODULE=backend.settings.production
    beat:
        environment:
            - DJANGO_SETTINGS_MODULE=backend.settings.production
