# Generated by Django 3.2 on 2021-05-14 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gappers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('ticker', models.CharField(max_length=10)),
                ('market', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('side', models.CharField(choices=[('SH', 'Short'), ('LO', 'Long')], max_length=2)),
                ('type', models.CharField(choices=[('DT', 'Day Trade'), ('SC', 'Scalp'), ('SW', 'Swing')], max_length=2)),
                ('pnl', models.DecimalField(blank=True, decimal_places=10, max_digits=17, null=True)),
                ('net', models.DecimalField(blank=True, decimal_places=10, max_digits=17, null=True)),
                ('max_size', models.PositiveIntegerField()),
                ('entries', models.PositiveIntegerField()),
                ('exits', models.PositiveIntegerField()),
                ('entry_price', models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True)),
                ('comissions', models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True)),
                ('calculated_comissions', models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True)),
                ('borrow_comissions', models.DecimalField(decimal_places=10, max_digits=16, null=True)),
                ('ecn_fees', models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('upgapper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gappers.upgapper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('last_time', models.DateTimeField(blank=True, null=True)),
                ('ticker', models.CharField(max_length=10)),
                ('action_raw', models.CharField(max_length=15)),
                ('action', models.CharField(choices=[('SH', 'Short'), ('BU', 'Buy'), ('SE', 'Sell')], max_length=2)),
                ('shares', models.IntegerField()),
                ('shares_executed', models.IntegerField()),
                ('shares_display', models.IntegerField()),
                ('expiration_raw', models.CharField(max_length=15)),
                ('status_raw', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('FI', 'Filled'), ('CA', 'Canceled'), ('RE', 'Rejected')], max_length=2)),
                ('type_raw', models.CharField(max_length=15)),
                ('type', models.CharField(choices=[('MA', 'Market'), ('LI', 'Limit'), ('SL', 'Stop Limit'), ('SM', 'Stop Market')], max_length=2)),
                ('price', models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True)),
                ('route', models.CharField(max_length=20)),
                ('expiration', models.CharField(max_length=50)),
                ('broker', models.CharField(max_length=30)),
                ('account', models.CharField(max_length=25)),
                ('broker_ord_id', models.CharField(max_length=50)),
                ('broker_info', models.CharField(max_length=50)),
                ('calculated_commission', models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True)),
                ('ecn_fees', models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True)),
                ('in_out', models.IntegerField(choices=[(1, 'In'), (2, 'Out')])),
                ('starter_order', models.BooleanField(default=False)),
                ('closing_order', models.BooleanField(default=False)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trades.trade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
