# Generated by Django 3.2 on 2021-05-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='entry_price',
            new_name='first_entry_price',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='exit_price',
            new_name='last_exit_price',
        ),
        migrations.AddField(
            model_name='trade',
            name='position',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='in_out',
            field=models.IntegerField(choices=[(1, 'In'), (2, 'Out')], null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shares',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='shares_display',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='shares_executed',
            field=models.PositiveIntegerField(),
        ),
    ]
