# Generated by Django 3.2 on 2021-07-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_trade_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='slug',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
