# Generated by Django 3.2 on 2021-05-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_auto_20210514_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='entries',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exits',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='max_size',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
