# Generated by Django 3.2 on 2021-07-02 01:12
import datetime
from django.db import migrations

def set_slug(apps, schema_editor):
    Trade = apps.get_model('trades', 'Trade')
    for trade in Trade.objects.all():
        small_uuid = trade.uuid.split('-')[0]
        p_or_l = 'profit' if trade.pnl >= 0 else 'loss'
        close_date = datetime.datetime.strftime(trade.end_time, '%b-%d-%Y').lower()
        trade.slug = '{ticker}-{pnl}-{p_or_l}-by-{username}-on-{close_date}-{small_uuid}'.format(
                                                ticker = trade.ticker,
                                                pnl = abs(int(trade.pnl)),
                                                p_or_l = p_or_l,
                                                username = trade.user.user_name,
                                                close_date = close_date,
                                                small_uuid = small_uuid)
        trade.save()






class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_trade_slug'),
    ]

    operations = [
        migrations.RunPython(set_slug,),
    ]
