# Generated by Django 3.2 on 2021-05-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_auto_20210515_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shares_display',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shares_executed',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
