# Generated by Django 3.2 on 2021-07-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_auto_20210702_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='closed_slug',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
