# Generated by Django 3.2 on 2021-05-15 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_ordersfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expiration_raw',
        ),
    ]
