# Generated by Django 3.2 on 2021-08-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_trade_closed_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='comments',
            field=models.TextField(default=''),
        ),
    ]
