# Generated by Django 3.2 on 2021-08-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_trade_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='comments',
            field=models.TextField(default='', null=True),
        ),
    ]
