# Generated by Django 3.2 on 2021-05-15 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0006_remove_order_expiration_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='broker_info',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='broker_ord_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('user', 'broker_ord_id', 'start_time')},
        ),
    ]
