# Generated by Django 3.2 on 2021-05-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_auto_20210515_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='pnl_accumulator',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=31, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='borrow_comissions',
            field=models.DecimalField(decimal_places=10, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='calculated_comissions',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='comissions',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='ecn_fees',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='net',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='pnl',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True),
        ),
    ]
