# Generated by Django 3.2 on 2021-09-08 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0008_daytradesgroupedbydaybyticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='grouped_day_trades',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trades.daytradesgroupedbydaybyticker'),
        ),
    ]
