# Generated by Django 3.2 on 2021-09-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0009_trade_grouped_day_trades'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='daytrade',
            field=models.BooleanField(default=False),
        ),
    ]
