# Generated by Django 3.2 on 2021-07-06 19:13

import charts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockBarDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(max_length=10)),
                ('timeframe', models.CharField(choices=[('1M', '1M'), ('5M', '5M'), ('1H', '1Hour'), ('1D', '1Day')], max_length=2)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('_file', models.FileField(upload_to=charts.models.create_path)),
            ],
        ),
    ]
