# Generated by Django 3.2 on 2021-09-08 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0010_trade_daytrade'),
        ('logs', '0002_tradetag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagTickerDayTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grouped_day_trades', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grouped_trades', to='trades.daytradesgroupedbydaybyticker')),
                ('tradetag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='logs.tradetag')),
            ],
        ),
    ]
