# Generated by Django 3.2 on 2021-09-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0010_trade_daytrade'),
        ('logs', '0003_tagtickerdaytrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradetag',
            name='ticker_date',
            field=models.ManyToManyField(through='logs.TagTickerDayTrade', to='trades.DayTradesGroupedByDayByTicker'),
        ),
    ]
