# Generated by Django 3.2 on 2021-09-15 02:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0004_tradetag_ticker_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tradetag',
            unique_together={('name', 'type', 'user')},
        ),
    ]
