# Generated by Django 3.1.4 on 2021-01-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('source_id', models.CharField(blank=True, max_length=400, null=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('provider_publish_time', models.DateTimeField()),
                ('provider_publish_time_epoc', models.IntegerField()),
                ('provider', models.CharField(max_length=100)),
                ('scrap_source', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=600)),
                ('title', models.CharField(max_length=800)),
                ('body', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('tickers', models.CharField(max_length=100)),
                ('authors', models.CharField(blank=True, max_length=200, null=True)),
                ('gmtOffSetMilliseconds', models.IntegerField()),
            ],
        ),
    ]
