# Generated by Django 3.2 on 2021-05-10 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gappers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('internal_source', models.CharField(max_length=50)),
                ('publish_date', models.DateTimeField()),
                ('publish_time_epoc', models.BigIntegerField(null=True)),
                ('source', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('body', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('tickers', models.CharField(max_length=400)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(max_length=900)),
                ('img_url', models.URLField(max_length=900)),
                ('gmtOffSetMilliseconds', models.IntegerField(blank=True, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=20)),
                ('down_gapper', models.ManyToManyField(blank=True, null=True, to='gappers.DownGapper')),
                ('up_gapper', models.ManyToManyField(blank=True, null=True, to='gappers.UpGapper')),
            ],
        ),
    ]
