# Generated by Django 3.1.4 on 2021-01-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gappers', '0001_initial'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='down_gapper',
            field=models.ManyToManyField(to='gappers.DownGapper'),
        ),
        migrations.AddField(
            model_name='news',
            name='up_gapper',
            field=models.ManyToManyField(to='gappers.UpGapper'),
        ),
    ]
