# Generated by Django 3.2 on 2021-05-11 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-publish_date', 'title']},
        ),
        migrations.AlterUniqueTogether(
            name='news',
            unique_together={('internal_source', 'title')},
        ),
    ]
