# Generated by Django 3.1.4 on 2021-01-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210115_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='gmtOffSetMilliseconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
