# Generated by Django 3.2 on 2021-05-12 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210511_2231'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='news',
            unique_together={('internal_source', 'title', 'publish_date')},
        ),
    ]
